openapi: 3.0.3
info:
  title: API Rebalanceamento
  description: "API para manter portifólio de ativos, carteiras, transações e contas\
    \ no mongodb"
  version: 1.0.1
servers:
- url: http://localhost:4201/api/v1
tags:
- name: Health
  description: Endpoints úteis para verificar saúde da aplicação
- name: Seguranca
  description: Endpoints de segurança
- name: Transacao
  description: CRUD para definição de transações
- name: Carteira
  description: CRUD para definição de carteiras
- name: Conta
  description: CRUD para definição de contas
- name: Consolidado
  description: Mantém o histórico consolidado mensal
- name: Cotacao
  description: Mantém cotação
paths:
  /health-check:
    get:
      x-swagger-router-controller: Health
      operationId: healthCheckGET
      tags:
      - Health
      responses:
        "200":
          description: Health status
          content:
            application/json:
              schema:
                type: object
  /auth:
    post:
      x-swagger-router-controller: Seguranca
      operationId: authPOST
      tags:
      - Seguranca
      summary: Autentica um serviço
      description: Retorna um token válido para as futuras requisições
      parameters:
      - name: X-API-KEY
        in: header
        description: Key
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Jwt Token
          content:
            text/plain:
              schema:
                type: string
                x-content-type: application/json
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - ApiKeyAuth: []
      
  /transacao:
    get:
      x-swagger-router-controller: Transacao
      operationId: transacaoGET
      tags:
      - Transacao
      summary: Lista as transacações
      description: Lista as transacações programadas do ano
      parameters:
      - in: query
        name: mes
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 12
      - in: query
        name: pago
        required: false
        description: Se informado, filtra apenas as transacações pagas
        schema:
          type: boolean
      - in: query
        name: categoria
        required: false
        description: Filtra pela categoria
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transacao'
                x-content-type: application/json
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    post:
      x-swagger-router-controller: Transacao
      operationId: transacaoPOST
      tags:
      - Transacao
      summary: Adiciona uma nova transação
      description: Adiciona uma nova transação
      requestBody:
        description: Cria uma nova transação
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transacao'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transacao'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    put:
      x-swagger-router-controller: Transacao
      operationId: transacaoPUT
      tags:
      - Transacao
      summary: Atualiza uma transação
      description: Atualiza uma transação identificada pelo seu id
      requestBody:
        description: Dados da transação
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transacao'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transacao'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
  
  /transacao/id/{transacaoId}:
    parameters:
    - name: transacaoId
      in: path
      description: ID da transacao
      required: true
      style: simple
      explode: false
      schema:
        type: string
    get:
      x-swagger-router-controller: Transacao
      operationId: transacaoIdGET
      tags:
      - Transacao
      summary: Busca os dados de uma transacao pelo Id
      description: Returna uma única transacao
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transacao'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    delete:
      x-swagger-router-controller: Transacao
      operationId: transacaoIdDELETE
      tags:
      - Transacao
      summary: Remove uma nova transacao
      description: Remove uma nova transacao
      responses:
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain

  /ativo:
    get:
      x-swagger-router-controller: Carteira
      operationId: ativoGET
      tags:
      - Carteira
      summary: Lista os ativos disponíveis
      description: Lista os ativos cadastrados
      parameters: 
      - in: query
        name: classe
        required: false
        schema:
          $ref: '#/components/schemas/Classe'
      - in: query
        name: nome
        description: Parte do nome
        example: GOOGL
        required: false
        schema:
          type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ativo'
                x-content-type: application/json
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    post:
      x-swagger-router-controller: Carteira
      operationId: ativoPOST
      tags:
      - Carteira
      summary: Adiciona um ativo
      description: Adiciona um ativo ao portifólio
      requestBody:
        description: Dados do Ativo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ativo'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ativo'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    put:
      x-swagger-router-controller: Carteira
      operationId: ativoPUT
      tags:
      - Carteira
      summary: Atualiza um ativo
      description: Atualiza um ativo identificado pelo seu id
      requestBody:
        description: Dados do ativo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ativo'
        required: true
      responses:
        "200":
          description: Successful operation
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
  /ativo/id/{ativoId}:
    parameters:
    - name: ativoId
      in: path
      description: Id do ativo
      required: true
      style: simple
      explode: false
      schema:
        type: string
    get:
      x-swagger-router-controller: Carteira
      operationId: ativoIdGET
      tags:
      - Carteira
      summary: Obtém um ativo
      description: Obtém um ativo pelo seu id
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ativo'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    delete:
      x-swagger-router-controller: Carteira
      operationId: ativoIdDELETE
      tags:
      - Carteira
      summary: Remove um ativo
      description: Remove um ativo identificado pelo seu id
      responses:
        "200":
          description: Successful operation
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
  /carteira:
    get:
      x-swagger-router-controller: Carteira
      operationId: carteiraGET
      tags:
      - Carteira
      summary: Obtém lista de carteiras do portifólio
      description: Recebe um array de Carteira
      parameters: 
      - in: query
        name: moeda
        required: false
        schema:
          $ref: '#/components/schemas/Moeda'
      - in: query
        name: classe
        required: false
        schema:
          $ref: '#/components/schemas/Classe'
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Carteira'
                x-content-type: application/json
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    post:
      x-swagger-router-controller: Carteira
      operationId: carteiraPOST
      tags:
      - Carteira
      summary: Adiciona uma carteira
      description: Adiciona uma carteira ao portifólio
      requestBody:
        description: Dados da carteira
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Carteira'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Carteira'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    put:
      x-swagger-router-controller: Carteira
      operationId: carteiraPUT
      tags:
      - Carteira
      summary: Atualiza uma carteira
      description: Atualiza uma carteira identificada pelo seu id
      requestBody:
        description: Dados da carteira
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Carteira'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Carteira'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
  /carteira/{carteiraId}:
    parameters:
    - name: carteiraId
      in: path
      description: Id da carteira
      required: true
      style: simple
      explode: false
      schema:
        type: string
    get:
      x-swagger-router-controller: Carteira
      operationId: carteiraIdGET
      tags:
      - Carteira
      summary: Obtém uma carteira
      description: Obtém uma carteira identificada pelo seu id
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Carteira'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    delete:
      x-swagger-router-controller: Carteira
      operationId: carteiraIdDELETE
      tags:
      - Carteira
      summary: Remove uma carteira
      description: Remove uma carteira identificada pelo seu id
      responses:
        "200":
          description: Successful operation
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
  /carteira/{carteiraId}/alocacao:
    parameters:
    - name: carteiraId
      in: path
      description: Id da carteira
      required: true
      style: simple
      explode: false
      schema:
        type: string
    get:
      x-swagger-router-controller: Carteira
      operationId: carteiraIdAlocacaoGET
      tags:
      - Carteira
      summary: Obtém as alocações dos ativos de uma carteira
      description: Obtém os ativos de uma carteira identificada pelo seu id
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarteiraAtivos'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    post:
      x-swagger-router-controller: Carteira
      operationId: carteiraIdAlocacaoPOST
      tags:
      - Carteira
      summary: Atualiza as alocações de um conjunto de ativos em uma carteira
      description: Atualiza as alocações de um conjunto de ativos em uma carteira
        identificada pelo seu id
      requestBody:
        description: Dados das alocações
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CarteiraAtivos'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarteiraAtivos'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
  /conta:
    get:
      x-swagger-router-controller: Conta
      operationId: contaGET
      tags:
      - Conta
      summary: Obtém lista de contas do portifólio
      description: Recebe um array de Conta
      parameters: 
      - in: query
        name: moeda
        required: false
        schema: 
          $ref: '#/components/schemas/Moeda'
      - in: query
        name: conta
        required: false
        schema:
          type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conta'
                x-content-type: application/json
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    post:
      x-swagger-router-controller: Conta
      operationId: contaPOST
      tags:
      - Conta
      summary: Adiciona uma conta
      description: Adiciona uma conta ao portifólio
      requestBody:
        description: Dados da conta
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Conta'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conta'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    put:
      x-swagger-router-controller: Conta
      operationId: contaPUT
      tags:
      - Conta
      summary: Atualiza uma conta
      description: Atualiza uma conta identificada pelo seu id
      requestBody:
        description: Dados da conta
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Conta'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conta'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
  
  /conta/id/{contaId}:
    parameters:
    - name: contaId
      in: path
      description: Id da conta
      required: true
      style: simple
      explode: false
      schema:
        type: string
    get:
      x-swagger-router-controller: Conta
      operationId: contaIdGET
      tags:
      - Conta
      summary: Obtém uma conta
      description: Obtém uma conta identificada pelo seu id
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Carteira'
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    delete:
      x-swagger-router-controller: Conta
      operationId: contaIdDELETE
      tags:
      - Conta
      summary: Remove uma conta
      description: Remove uma conta identificada pelo seu id
      responses:
        "200":
          description: Successful operation
        "400":
          description: The specified resource is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The specified resource was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
        
  /contas/saldoTotal:
    get:
      x-swagger-router-controller: Conta
      operationId: contasSaldoTotalGET
      tags:
      - Conta
      summary: Obtém o saldo total
      description: Soma todos os saldos das contas
      responses:
        "200":
          description: O saldo total das contas
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
  
  /consolidado:
    get:
      x-swagger-router-controller: Consolidado
      operationId: consolidadoGET
      tags:
      - Consolidado
      summary: Obtém o consolidado de um período
      description: Retorna o consolidado dentro de um período ou o conteúdo total da base
      parameters: 
      - name: inicio
        in: query
        required: false
        explode: false
        description: Início do período da consulta no formato yyyyMM
        example: 202105
        schema:
          type: number
          minimum: 190101
          maximum: 210012
      - name: fim
        in: query
        required: false
        explode: false
        description: Final do período da consulta no formato yyyyMM
        example: 202105
        schema:
          type: number
          minimum: 190101
          maximum: 210012
      responses:
        "200":
          description: A lista de consolidados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Consolidado'
                x-content-type: application/json
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    post:
      x-swagger-router-controller: Consolidado
      operationId: consolidadoPOST
      tags:
      - Consolidado
      summary: Atualiza consolidado enviando conjunto para um mês-ano
      description: Controla para manter apenas um consolidado por mês-ano
      requestBody:
        description: Conjunto de consolidados
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Consolidado'
      responses:
        "200":
          description: A lista de consolidados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Consolidado'
                x-content-type: application/json
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
        
  /consolidado/tipo/{tipo}:
    get:
      x-swagger-router-controller: Consolidado
      operationId: consolidadoTipoGET
      tags:
      - Consolidado
      summary: Obtém o consolidado de um período
      description: Retorna o consolidado dentro de um período ou o conteúdo total da base
      parameters: 
      - name: tipo
        in: path
        description: Tipo do consolidado
        required: true
        schema:
          $ref: '#/components/schemas/Classe'
      - name: inicio
        in: query
        required: true
        explode: false
        description: Início do período da consulta no formato yyyyMM
        example: 202105
        schema:
          type: number
          minimum: 190101
          maximum: 210012
      - name: fim
        in: query
        required: true
        explode: false
        description: Final do período da consulta no formato yyyyMM
        example: 202105
        schema:
          type: number
          minimum: 190101
          maximum: 210012
      responses:
        "200":
          description: A lista de consolidados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Consolidado'
                x-content-type: application/json
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
  
  /consolidado/gerar:
    post:
      x-swagger-router-controller: Consolidado
      operationId: consolidadoGerarPOST
      tags:
      - Consolidado
      summary: Gera o consolidado no servidor
      description: Recupera todos os tipos de ativos e contas e consolida pela posição atual no mês corrente
      parameters:
      - name: anoMes
        in: query
        description: anoMes a ser consolidado no formato yyyyMM
        example: 202105
        required: false
        schema:
          type: number
          minimum: 190101
          maximum: 210012
      responses:
        "200":
          description: Geração BRLizada
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
        "422":
          description: The specified resource is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - bearerAuth:
        - write:domain
        - read:domain

################################################################ COTACAO        
  /cotacao/summary/{simbolo}:
    get:
      x-swagger-router-controller: Cotacao
      operationId: cotacaoSummaryGET
      tags:
      - Cotacao
      summary: Obtém cotações do Yahoo Finance chamando API web
      description: Recupera a cotação atual de um ou mais símbolos
      parameters: 
      - name: simbolo
        in: path
        description: Símbolo da(s) cotação(ões) a ser(em) pesquisada(s
        required: true
        schema:
          oneOf:
          - type: string
          - type: array
            items:
              type: object
      responses:
        "200":
          description: Obteve cotação
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
      security:
      - bearerAuth:
        - write:domain
        - read:domain
        
  /cotacao/yahoo/{simbolo}:
    get:
      x-swagger-router-controller: Cotacao
      operationId: cotacaoYahooGET
      tags:
      - Cotacao
      summary: Obtém cotações do Yahoo Finance
      description: Recupera a cotação atual de um ou mais símbolos
      parameters: 
      - name: simbolo
        in: path
        description: Símbolo da(s) cotação(ões) a ser(em) pesquisada(s
        required: true
        schema:
          oneOf:
          - type: string
          - type: array
            items:
              type: object
      responses:
        "200":
          description: Obteve cotação
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
      security:
      - bearerAuth:
        - write:domain
        - read:domain
        
  /cotacao/batch/cotacoes:
    get:
      x-swagger-router-controller: Cotacao
      operationId: atualizarCotacoesBatchGET
      tags:
      - Cotacao
      summary: Recupera o status de processamento de atualizações das cotações
      description: Retorna um objeto com informações dos processamentos do dia
      responses:
        "200":
          description: Obteve cotação
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    put:
      x-swagger-router-controller: Cotacao
      operationId: atualizarCotacoesBatchPUT
      tags:
      - Cotacao
      summary: Atualiza cotações a partir de consulta no Yahoo Finance
      description: Recupera a cotação atual de um ou mais símbolos
      responses:
        "200":
          description: Obteve cotação
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
      security:
      - bearerAuth:
        - write:domain
        - read:domain
      
  /cotacao/batch/cotacao/{simbolo}:
    put:
      x-swagger-router-controller: Cotacao
      operationId: atualizarCotacaoBatchPUT
      tags:
      - Cotacao
      summary: Obtém cotações do Yahoo Finance e atualiza as cotações na base de dados
      description: Recupera a cotação atual de um ou mais símbolos e registra o resultado na base de dados
      parameters: 
      - name: simbolo
        in: path
        description: Símbolo da(s) cotação(ões) a ser(em) pesquisada(s
        required: true
        schema:
          oneOf:
          - type: string
      responses:
        "200":
          description: Obteve cotação
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
      security:
      - bearerAuth:
        - write:domain
        - read:domain
      
  /cotacao:
    get:
      x-swagger-router-controller: Cotacao
      operationId: cotacaoGET
      tags:
      - Cotacao
      summary: Obtém cotações armazenadas no banco de dados
      description: Recupera a cotação atual de um ou mais símbolos
      parameters: 
      - name: data
        in: query
        description: Data da cotação. Quando não informado, assume a data corrente
        required: false
        schema:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
          example: '2025-03-20'
      - name: simbolo
        in: query
        description: Símbolo das cotações a serem pesquisadas, separados por vírgula
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Obteve cotação
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    post:
      x-swagger-router-controller: Cotacao
      operationId: cotacaoPOST
      tags:
      - Cotacao
      summary: Adiciona cotação ao banco de dados
      description: Adiciona cotação ao banco de dados
      requestBody:
        description: Dados da conta
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cotacao'
      responses:
        "201":
          description: Cotação adicionada com sucesso
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
        "400":
          description: O objeto de cotação não é válido
      security:
      - bearerAuth:
        - write:domain
        - read:domain
  
  /aporte:
    get:
      x-swagger-router-controller: Investimento
      operationId: aporteGET
      tags:
      - Investimento
      summary: Obtém aportes armazenados no banco de dados
      description: Recupera os aportes realizados
      parameters:
      - name: carteiraId
        in: query
        description: Identificador da carteira
        required: false
        schema:
          type: string
      - name: data
        in: query
        description: Data do aporte. Quando não informado, assume a data corrente
        required: false
        schema:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
      responses:
        "200":
          description: Obteve aportes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aporte'
        "400":
          description: Parâmetro inválido
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    
    post:
      x-swagger-router-controller: Investimento
      operationId: aportePOST
      tags:
      - Investimento
      summary: Adiciona aporte ao banco de dados
      description: Adiciona aporte ao banco de dados
      requestBody:
        description: Dados do aporte
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aporte'
      responses:
        "201":
          description: Aporte adicionado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aporte'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
        
  /aporte/{id}:
    parameters:
    - name: id
      in: path
      description: Identificador do aporte
      required: true
      schema:
        type: string
    put:
      x-swagger-router-controller: Investimento
      operationId: aportePUT
      tags:
      - Investimento
      summary: Atualiza aporte no banco de dados
      description: Atualiza aporte no banco de dados
      requestBody:
        description: Dados do aporte
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aporte'
      responses:
        "200":
          description: Aporte atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aporte'
      security:
      - bearerAuth:
        - write:domain
        - read:domain

    delete:
      x-swagger-router-controller: Investimento
      operationId: aporteDELETE
      tags:
      - Investimento
      summary: Remove aporte do banco de dados
      description: Remove aporte do banco de dados
      responses:
        "204":
          description: Aporte removido com sucesso
        "404":
          description: Aporte não encontrado
      security:
      - bearerAuth:
        - write:domain
        - read:domain

  /provento:
    get:
      x-swagger-router-controller: Investimento
      operationId: proventoGET
      tags:
      - Investimento
      summary: Obtém proventos armazenados no banco de dados
      description: Recupera os proventos emitidos
      parameters:
      - name: dataInicio
        in: query
        description: Data inicial do período dos proventos
        required: false
        schema:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
      - name: dataFinal
        in: query
        description: Data final do período dos proventos
        required: false
        schema:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
      - name: agregado
        in: query
        description: Agregado dos proventos. Por padrão, é 'false'
        required: false
        schema:
          type: boolean
          default: false
      responses:
        "200":
          description: Obteve proventos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Provento'
        "400":
            description: Parâmetro inválido
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    post:
      x-swagger-router-controller: Investimento
      operationId: proventoPOST
      tags:
      - Investimento
      summary: Adiciona provento ao banco de dados
      description: Adiciona provento ao banco de dados
      requestBody:
        description: Dados do provento
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Provento'
      responses:
        "201":
          description: Provento adicionado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provento'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
  
  /provento/{id}:
    parameters:
    - name: id
      in: path
      description: Identificador do provento
      required: true
      schema:
        type: string
        properties:
          id:
            type: string
      example: 'c57b6004-5605-448'
    put:
      x-swagger-router-controller: Investimento
      operationId: proventoPUT
      tags:
      - Investimento
      summary: Atualiza provento no banco de dados
      description: Atualiza provento no banco de dados
      requestBody:
        description: Dados do provento
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Provento'
      responses:
        "200":
          description: Provento atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provento'
        "404":
          description: Provento não encontrado
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    
    delete:
      x-swagger-router-controller: Investimento
      operationId: proventoDELETE
      tags:
      - Investimento
      summary: Remove provento do banco de dados
      description: Remove provento do banco de dados
      responses:
        "204":
          description: Provento removido com sucesso
        "404":
          description: Provento não encontrado
      security:
      - bearerAuth:
        - write:domain
        - read:domain
  
  /retirada:
    get:
      x-swagger-router-controller: Investimento
      operationId: retiradaGET
      tags:
      - Investimento
      summary: Obtém retiradas armazenadas no banco de dados
      description: Recupera as retiradas realizadas
      parameters:
      - name: dataInicio
        in: query
        description: Data inicial do período das retiradas
        required: false
        schema:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
      - name: dataFinal
        in: query
        description: Data final do período das retiradas
        required: false
        schema:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
      responses:
        "200":
          description: Obteve retiradas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Retirada'
        "400":
          description: Parâmetro inválido
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    
    post:
      x-swagger-router-controller: Investimento
      operationId: retiradaPOST
      tags:
      - Investimento
      summary: Adiciona retirada ao banco de dados
      description: Adiciona retirada ao banco de dados
      requestBody:
        description: Dados da retirada
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Retirada'
      responses:
        "201":
          description: Retirada adicionada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Retirada'
      security:
      - bearerAuth:
        - write:domain
        - read:domain
  
  /retirada/{id}:
    parameters:
    - name: id
      in: path
      description: Identificador da retirada
      required: true
      schema:
        type: string
        example: 'c57b6004-5605-448'
    put:
      x-swagger-router-controller: Investimento
      operationId: retiradaPUT
      tags:
      - Investimento
      summary: Atualiza retirada no banco de dados
      description: Atualiza retirada no banco de dados
      requestBody:
        description: Dados da retirada
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Retirada'
      responses:
        "200":
          description: Retirada atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Retirada'
        "404":
          description: Retirada não encontrada
      security:
      - bearerAuth:
        - write:domain
        - read:domain
    
    delete:
      x-swagger-router-controller: Investimento
      operationId: retiradaDELETE
      tags:
      - Investimento
      summary: Remove retirada do banco de dados
      description: Remove retirada do banco de dados
      responses:
        "204":
          description: Retirada removida com sucesso
        "404":
          description: Retirada não encontrada
      security:
      - bearerAuth:
        - write:domain
        - read:domain
      

components:
  schemas:
    Moeda:
      type: string
      enum:
      - BRL
      - USD
      - USDT
    Classe:
      type: string
      enum:
      - Moeda
      - Acao
      - FII
      - PosFixada
      - CDB
      - RF
      - ETF
      - Referencia
      - Cripto
    TipoConta:
      type: string
      enum:
      - CORRENTE
      - INVESTIMENTO
      - POUPANCA
      - CARTAO
      - OUTROS
    MetodoCotacao:
      type: string
      enum:
      - manual
      - yahoo
      - tesouro
      - referencia
    Transacao:
      type: object
      required:
        - descricao
        - valor
        - periodicidade
        - dataInicial
        - tipoTransacao
        - liquidacao
      properties:
        _id:
          type: string
          description: Identificador da Transação
        descricao:
          maxLength: 200
          minLength: 3
          type: string
          example: Impostos
        valor:
          type: number
          format: double
          example: 202.1
        periodicidade:
          type: string
          example: SEMESTRAL
          enum:
            - UNICO
            - SEMANAL
            - QUINZENAL
            - MENSAL
            - TRIMESTRAL
            - SEMESTRAL
            - ANUAL
        tipoTransacao:
          type: string
          example: DEBITO
          enum:
            - DEBITO
            - CREDITO
            - JCP
            - DIVIDENDO
            - BONUS
            - EXTRA
        dataInicial:
          type: string
          format: date
          example: 2020-01-01
        dataFinal:
          type: string
          format: date
          nullable: true
          example: 2020-01-01
        dataLancamento:
          type: string
          format: date
          nullable: true
          example: 2020-01-01
        origem:
          type: string
          minLength: 8
          nullable: true
          description: Referência à transação de origem da recorrência 
        categoria:
          type: string
          example: Custo Fixo
          nullable: true
        liquidacao:
          $ref: '#/components/schemas/TipoConta'
        contaLiquidacao:
          type: string
          nullable: true
          minLength: 8
          description: Referência à conta de liquidação
    Carteira:
      required:
      - classe
      - moeda
      - nome
      - objetivo
      type: object
      properties:
        _id:
          type: string
          description: Id da Carteira
        nome:
          maxLength: 200
          minLength: 3
          type: string
          description: Nome da carteira
          example: Ações
        moeda:
          $ref: '#/components/schemas/Moeda'
        objetivo:
          type: number
          description: Percentual da alocação desta carteira no portifólio
          minimum: 0
          maximum: 1
          example: 0.01
          format: double
        classe:
          $ref: '#/components/schemas/Classe'
        ativos:
          $ref: '#/components/schemas/CarteiraAtivos'
      example:
        objetivo: 0.01
        classe: ACAO
        moeda: BRL
        nome: Ações
        id: 100
    Ativo:
      required:
      - sigla
      - nome
      - tipo
      - moeda
      - setor
      - metodo
      type: object
      properties:
        _id:
          type: string
          description: Id do Ativo
        sigla:
          minLength: 1
          type: string
          example: NYSE:GOOGL
        siglaYahoo:
          nullable: true
          type: string
          example: NYSE:GOOGL
        nome:
          minLength: 3
          type: string
          example: Google na NYSE
        moeda:
          $ref: '#/components/schemas/Moeda'
        setor:
          minLength: 3
          type: string
          example: Tecnologia
        tipo:
          $ref: '#/components/schemas/Classe'
        metodo:
          $ref: '#/components/schemas/MetodoCotacao'
        referencia:
          type: object
          required:
            - id
            - tipo
          properties:
            id:
              type: string
              description: Id da referência
              example: 43ed222fcc12d
            tipo:
              type: string
              description: Tipo da referência
              example: CARTEIRA
      example:
        simbolo: NYSE:GOOGL
        setor: Tecnologia
        ativo: GOOGLE
        tipo: Acao
        moeda: BRL
        id: 100
        descricao: Google na NYSE
    CarteiraAtivos:
      type: array
      items:
        type: object
        required: 
          - ativoId
          - objetivo
          - quantidade
          - vlInicial
        properties:
          ativoId:
            type: string
            description: Id do ativo
            example: 100
          objetivo:
            type: number
            format: double
            minimum: 0
            maximum: 1
            description: Percentual do objetivo do ativo na carteira
            example: 0.5
          quantidade:
            type: number
            format: double
          vlInicial:
            type: number
            format: double
          vlAtual:
            type: number
            format: double
    Conta:
      required:
      - conta
      - moeda
      - saldo
      - tipo
      type: object
      properties:
        _id:
          type: string
        conta:
          maxLength: 50
          minLength: 2
          type: string
          example: Itaú
        saldo:
          type: number
          format: double
          example: 150.23
        moeda:
          $ref: '#/components/schemas/Moeda'
        tipo:
          $ref: '#/components/schemas/TipoConta'
      example:
        moeda: BRL
        conta: Itaú
        id: 15
        saldo: 150.23
    Consolidado:
      required:
      - idRef
      - tipo
      - valor
      - anoMes
      type: object
      properties:
        _id:
          type: string
        idRef:
          type: string
        tipo:
          $ref: '#/components/schemas/Classe'
        valor:
          type: number
        anoMes:
          type: number
          minimum: 190101
          maximum: 210012
    Cotacao:
      required:
      - simbolo
      - data
      - preco
      - moeda
      type: object
      properties:
        _id:
          type: string
          description: Id da Cotacão
        simbolo:
          type: string
          description: Símbolo da Cotação
        manual:
          type: boolean
          description: true quando for uma atualização manual
        data:
          type: string
          format: date
          example: 2020-01-01
        dataColeta:
          type: string
          format: date
          example: 2020-01-01
        preco:
          type: number
          format: double
          description: valor da cotação
        moeda:
          $ref: '#/components/schemas/Moeda'

    Aporte:
      required:
      - idCarteira
      - idAtivo
      - data
      - quantidade
      - valorUnitario
      - total
      type: object
      properties:
        _id:
          type: string
        idCarteira:
          type: string
        idAtivo:
          type: string
        data:
          type: string
          format: date
        quantidade:
          type: number
          format: double
        valorUnitario:
          type: number
          format: double
        total:
          type: number
          format: double
      example:
        idCarteira: c57b6004-5605-448
        idAtivo: c57b6004-5605-448
        data: 2020-01-01
        quantidade: 10
        valorUnitario: 100.00
        total: 1000.00

    TipoProvento:
      type: string
      enum:
        - Dividendo
        - JCP
        - Aluguel
        - Taxa
        - Bonus
        - Outros
    
    Provento:
      required:
      - idAtivo
      - idConta
      - data
      - tipo
      - total
      type: object
      properties:
        _id:
          type: string
        idAtivo:
          type: string
        idConta:
          type: string
        data:
          type: string
          format: date
        tipo:
          $ref: '#/components/schemas/TipoProvento'
        total:
          type: number
          format: double
      example:
        idAtivo: c57b6004-5605-448
        idConta: c57b6004-5605-448
        data: 2020-01-01
        tipo: Dividendo
        total: 100.00

    Retirada:
      required:
      - data
      - valor
      type: object
      properties:
        data:
          type: string
          format: date
        valor:
          type: number
          format: double
            
    Error:
      type: object
      
  responses:
    ValidationError:
      description: The specified resource is not valid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InvalidRequest:
      description: The specified resource is invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  requestBodies:
    Carteira:
      description: Carteira para ser adicionada ao portifólio
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Carteira'
    Ativo:
      description: Ativo para ser adicionado ao portifólio
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Ativo'
    Conta:
      description: Conta para ser adicionada ao portifólio
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Conta'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-KEY
      in: header
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
